name: Generate Readme Translations
on:
    push:
        - 1222--README-ci-auto-translation
jobs:
    translation:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                language: [
                    {code: 'CN', name: 'Chinese'},
                    {code: 'DE', name: 'German'},
                    {code: 'ES', name: 'Spanish'},
                    {code: 'FR', name: 'French'},
                    {code: 'HE', name: 'Hebrew'},
                    {code: 'IT', name: 'Italian'},
                    {code: 'JA', name: 'Japanese'},
                    {code: 'KOR', name: 'Korean'},
                    {code: 'PTBR', name: 'Portuguese (Brazil)'},
                    {code: 'RU', name: 'Russian'},
                    {code: 'TH', name: 'Thai'},
                    {code: 'TR', name: 'Turkish'},
                    {code: 'VI', name: 'Vietnamese'}
                ]
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main
                  token: ${{ secrets.GH_TOKEN }}

            - name: Read README content
              id: readme
              run: |
                content=$(cat README.md)
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "content=$content" >> $GITHUB_OUTPUT

            - name: Translate to ${{ matrix.language.name }}
              uses: 0xjord4n/aixion@v1.0.0
              id: aixion
              with:
                config: >
                  {
                    "provider": "openai",
                    "provider_options": {
                      "api_key": "${{ secrets.OPENAI_API_KEY }}"
                    },
                    "messages": [
                      {
                        "role": "system",
                        "content": "You will be provided with a markdown file in English, and your task is to translate it into ${{ matrix.language.name }}."
                      },
                      {
                        "role": "user",
                        "content": "${{ steps.readme.outputs.content }}"
                      }
                    ],
                    "model": "gpt-4o"
                  }

            - name: Save translation
              run: |
                mv translated.md README_${{ matrix.language.code }}.md

            - name: List README translations
              run: ls README_*.md || echo "No translation files found"

            - name: Commit translations
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update ${{ matrix.language.name }} translation"
                  branch: main
                  file_pattern: "README_${{ matrix.language.code }}.md"
                  commit_author: "GitHub Action <actions@github.com>"
